package net.ninemm.upms.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleOperationRel<M extends BaseRoleOperationRel<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setOperationId(java.lang.String operationId) {
		set("operation_id", operationId);
	}
	
	public java.lang.String getOperationId() {
		return getStr("operation_id");
	}

	public void setRoleId(java.lang.String roleId) {
		set("role_id", roleId);
	}
	
	public java.lang.String getRoleId() {
		return getStr("role_id");
	}

	public void setModuleId(java.lang.String moduleId) {
		set("module_id", moduleId);
	}

	public java.lang.String getModuleId() {
		return getStr("module_id");
	}

}
