package net.ninemm.upms.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemLog<M extends BaseSystemLog<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
	}
	
	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}
	
	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public void setActionStartDate(java.util.Date actionStartDate) {
		set("action_start_date", actionStartDate);
	}
	
	public java.util.Date getActionStartDate() {
		return get("action_start_date");
	}

	public void setActionEndDate(java.util.Date actionEndDate) {
		set("action_end_date", actionEndDate);
	}
	
	public java.util.Date getActionEndDate() {
		return get("action_end_date");
	}

	public void setActionCostTime(java.lang.Integer actionCostTime) {
		set("action_cost_time", actionCostTime);
	}
	
	public java.lang.Integer getActionCostTime() {
		return getInt("action_cost_time");
	}

	public void setViewCostTime(java.lang.Integer viewCostTime) {
		set("view_cost_time", viewCostTime);
	}
	
	public java.lang.Integer getViewCostTime() {
		return getInt("view_cost_time");
	}

	public void setTotalCostTime(java.lang.Integer totalCostTime) {
		set("total_cost_time", totalCostTime);
	}
	
	public java.lang.Integer getTotalCostTime() {
		return getInt("total_cost_time");
	}

	public void setCause(java.lang.String cause) {
		set("cause", cause);
	}
	
	public java.lang.String getCause() {
		return getStr("cause");
	}

	public void setCookie(java.lang.String cookie) {
		set("cookie", cookie);
	}
	
	public java.lang.String getCookie() {
		return getStr("cookie");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public void setMethod(java.lang.String method) {
		set("method", method);
	}
	
	public java.lang.String getMethod() {
		return getStr("method");
	}

	public void setReferer(java.lang.String referer) {
		set("referer", referer);
	}
	
	public java.lang.String getReferer() {
		return getStr("referer");
	}

	public void setRequestPath(java.lang.String requestPath) {
		set("request_path", requestPath);
	}
	
	public java.lang.String getRequestPath() {
		return getStr("request_path");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setUserAgent(java.lang.String userAgent) {
		set("user_agent", userAgent);
	}
	
	public java.lang.String getUserAgent() {
		return getStr("user_agent");
	}

	public void setOperationId(java.lang.String operationId) {
		set("operation_id", operationId);
	}
	
	public java.lang.String getOperationId() {
		return getStr("operation_id");
	}

	public void setAccept(java.lang.String accept) {
		set("accept", accept);
	}
	
	public java.lang.String getAccept() {
		return getStr("accept");
	}

	public void setAcceptEncoding(java.lang.String acceptEncoding) {
		set("accept_encoding", acceptEncoding);
	}
	
	public java.lang.String getAcceptEncoding() {
		return getStr("accept_encoding");
	}

	public void setAcceptLang(java.lang.String acceptLang) {
		set("accept_lang", acceptLang);
	}
	
	public java.lang.String getAcceptLang() {
		return getStr("accept_lang");
	}

	public void setConnection(java.lang.String connection) {
		set("connection", connection);
	}
	
	public java.lang.String getConnection() {
		return getStr("connection");
	}

	public void setHost(java.lang.String host) {
		set("host", host);
	}
	
	public java.lang.String getHost() {
		return getStr("host");
	}

	public void setXrequestedwith(java.lang.String xrequestedwith) {
		set("xrequestedwith", xrequestedwith);
	}
	
	public java.lang.String getXrequestedwith() {
		return getStr("xrequestedwith");
	}

	public void setPvids(java.lang.String pvids) {
		set("pvids", pvids);
	}
	
	public java.lang.String getPvids() {
		return getStr("pvids");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
