package net.ninemm.upms.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}
	
	public java.lang.String getRealname() {
		return getStr("realname");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}
	
	public java.lang.String getNickname() {
		return getStr("nickname");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}
	
	public java.lang.String getSalt() {
		return getStr("salt");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setUnableDate(java.util.Date unableDate) {
		set("unable_date", unableDate);
	}
	
	public java.util.Date getUnableDate() {
		return get("unable_date");
	}

	public void setDepartmentId(java.lang.String departmentId) {
		set("department_id", departmentId);
	}
	
	public java.lang.String getDepartmentId() {
		return getStr("department_id");
	}

	public void setDepartmentName(java.lang.String departmentName) {
		set("department_name", departmentName);
	}
	
	public java.lang.String getDepartmentName() {
		return getStr("department_name");
	}

	public void setStationId(java.lang.String stationId) {
		set("station_id", stationId);
	}
	
	public java.lang.String getStationId() {
		return getStr("station_id");
	}

	public void setStationName(java.lang.String stationName) {
		set("station_name", stationName);
	}
	
	public java.lang.String getStationName() {
		return getStr("station_name");
	}

	public void setGroupId(java.lang.String groupId) {
		set("group_id", groupId);
	}
	
	public java.lang.String getGroupId() {
		return getStr("group_id");
	}

	public void setGroupName(java.lang.String groupName) {
		set("group_name", groupName);
	}
	
	public java.lang.String getGroupName() {
		return getStr("group_name");
	}

	public void setDeptIds(java.lang.String deptIds) {
		set("dept_ids", deptIds);
	}
	
	public java.lang.String getDeptIds() {
		return getStr("dept_ids");
	}

	public void setDeptNames(java.lang.String deptNames) {
		set("dept_names", deptNames);
	}
	
	public java.lang.String getDeptNames() {
		return getStr("dept_names");
	}

	public void setUserIds(java.lang.String userIds) {
		set("user_ids", userIds);
	}
	
	public java.lang.String getUserIds() {
		return getStr("user_ids");
	}

	public void setUserNames(java.lang.String userNames) {
		set("user_names", userNames);
	}
	
	public java.lang.String getUserNames() {
		return getStr("user_names");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}
	
	public java.lang.String getProvince() {
		return getStr("province");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

	public void setRegion(java.lang.String region) {
		set("region", region);
	}
	
	public java.lang.String getRegion() {
		return getStr("region");
	}

	public void setDataArea(java.lang.String dataArea) {
		set("data_area", dataArea);
	}
	
	public java.lang.String getDataArea() {
		return getStr("data_area");
	}

	public void setWechatOpenId(java.lang.String wechatOpenId) {
		set("wx_open_id", wechatOpenId);
	}
	
	public java.lang.String getWechatOpenId() {
		return getStr("wx_open_id");
	}

	public void setWechatUserid(java.lang.String wechatUserid) {
		set("qywx_open_id", wechatUserid);
	}
	
	public java.lang.String getWechatUserid() {
		return getStr("qywx_open_id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
