package net.ninemm.upms.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOperation<M extends BaseOperation<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setModuleId(java.lang.String moduleId) {
		set("module_id", moduleId);
	}
	
	public java.lang.String getModuleId() {
		return getStr("module_id");
	}

	public void setModuleName(java.lang.String moduleName) {
		set("module_name", moduleName);
	}
	
	public java.lang.String getModuleName() {
		return getStr("module_name");
	}

	public void setOperationName(java.lang.String operationName) {
		set("operation_name", operationName);
	}
	
	public java.lang.String getOperationName() {
		return getStr("operation_name");
	}

	public void setOperationCode(java.lang.String operationCode) {
		set("operation_code", operationCode);
	}
	
	public java.lang.String getOperationCode() {
		return getStr("operation_code");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public void setIsPrivilege(java.lang.Integer isPrivilege) {
		set("is_privilege", isPrivilege);
	}
	
	public java.lang.Integer getIsPrivilege() {
		return getInt("is_privilege");
	}

	public void setIsSplitePage(java.lang.Integer isSplitePage) {
		set("is_splite_page", isSplitePage);
	}
	
	public java.lang.Integer getIsSplitePage() {
		return getInt("is_splite_page");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setOrderList(java.lang.Integer orderList) {
		set("order_list", orderList);
	}
	
	public java.lang.Integer getOrderList() {
		return getInt("order_list");
	}

	public void setDeptId(java.lang.String deptId) {
		set("dept_id", deptId);
	}
	
	public java.lang.String getDeptId() {
		return getStr("dept_id");
	}

	public void setDataArea(java.lang.String dataArea) {
		set("data_area", dataArea);
	}
	
	public java.lang.String getDataArea() {
		return getStr("data_area");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
