package net.ninemm.upms.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOption<M extends BaseOption<M>> extends JbootModel<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setOptionKey(java.lang.String optionKey) {
		set("option_key", optionKey);
	}
	
	public java.lang.String getOptionKey() {
		return getStr("option_key");
	}

	public void setOptionValue(java.lang.String optionValue) {
		set("option_value", optionValue);
	}
	
	public java.lang.String getOptionValue() {
		return getStr("option_value");
	}

	public void setSellerId(java.lang.String sellerId) {
		set("seller_id", sellerId);
	}
	
	public java.lang.String getSellerId() {
		return getStr("seller_id");
	}

}
