package net.ninemm.upms.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.upms.service.model.base.BaseDepartment;

/**
 * Generated by Jboot.
 */
@Table(tableName = "upms_department", primaryKey = "id")
public class Department extends BaseDepartment<Department> {
	
}
