package net.ninemm.upms.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.upms.service.model.base.BaseDict;

/**
 * Generated by Jboot.
 */
@Table(tableName = "upms_dict", primaryKey = "id")
public class Dict extends BaseDict<Dict> {

}
