package net.ninemm.upms.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.upms.service.model.base.BaseDictType;

/**
 * Generated by Jboot.
 */
@Table(tableName = "upms_dict_type", primaryKey = "id")
public class DictType extends BaseDictType<DictType> {
	
}
