package net.ninemm.upms.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.upms.service.model.base.BaseGroup;

/**
 * Generated by Jboot.
 */
@Table(tableName = "upms_group", primaryKey = "id")
public class Group extends BaseGroup<Group> {
	
}
