package net.ninemm.upms.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.upms.service.model.base.BaseGroupRoleRel;

/**
 * Generated by Jboot.
 */
@Table(tableName = "upms_group_role_rel", primaryKey = "id")
public class GroupRoleRel extends BaseGroupRoleRel<GroupRoleRel> {
	
}
