package net.ninemm.upms.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.upms.service.model.base.BaseGroup;

/**
 * Generated by Jboot.
 * @author eric
 */
@Table(tableName = "upms_group", primaryKey = "id")
public class Group extends BaseGroup<Group> {

    public static final String CACHE_NAME = "upms_group";
}
