package net.ninemm.upms.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.upms.service.model.base.BaseMenu;

/**
 * Generated by Jboot.
 */
@Table(tableName = "upms_menu", primaryKey = "id")
public class Menu extends BaseMenu<Menu> {

    public static final String CACHE_NAME = "upms_menu";
}
