package net.ninemm.upms.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.upms.service.model.base.BaseModule;

/**
 * Generated by Jboot.
 */
@Table(tableName = "upms_module", primaryKey = "id")
public class Module extends BaseModule<Module> {

    public Module getParent() {
        return findById(getParentId());
    }
}
