package net.ninemm.upms.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.upms.service.model.base.BaseOperation;

/**
 * Generated by Jboot.
 */
@Table(tableName = "upms_operation", primaryKey = "id")
public class Operation extends BaseOperation<Operation> {
	
}
