package net.ninemm.upms.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.upms.service.model.base.BaseOption;

/**
 * Generated by Jboot.
 */
@Table(tableName = "upms_option", primaryKey = "id")
public class Option extends BaseOption<Option> {
	
}
