package net.ninemm.upms.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.upms.service.model.base.BaseRoleOperationRel;

/**
 * Generated by Jboot.
 */
@Table(tableName = "upms_role_operation_rel", primaryKey = "id")
public class RoleOperationRel extends BaseRoleOperationRel<RoleOperationRel> {
	
}
