package net.ninemm.upms.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.upms.service.model.base.BaseSeller;

/**
 * Generated by Jboot.
 */
@Table(tableName = "upms_seller", primaryKey = "id")
public class Seller extends BaseSeller<Seller> {

	public static final String CACHE_NAME = "upms_seller";
}
