package net.ninemm.upms.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.upms.service.model.base.BaseStationOperationRel;

/**
 * Generated by Jboot.
 */
@Table(tableName = "upms_station_operation_rel", primaryKey = "id")
public class StationOperationRel extends BaseStationOperationRel<StationOperationRel> {
	
}
