package net.ninemm.upms.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.upms.service.model.base.BaseSystems;

/**
 * Generated by Jboot.
 */
@Table(tableName = "upms_systems", primaryKey = "id")
public class Systems extends BaseSystems<Systems> {

    public static final String CACHE_NAME = "upms_systems";

    public static final String CACHE_SELECT_LIST_KEY = "select:list";

}
