package net.ninemm.upms.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.upms.service.model.base.BaseSystemLog;

/**
 * Generated by Jboot.
 */
@Table(tableName = "upms_system_log", primaryKey = "id")
public class SystemLog extends BaseSystemLog<SystemLog> {
	
}
