package net.ninemm.upms.service.model;

import com.google.common.base.Splitter;
import io.jboot.db.annotation.Table;
import net.ninemm.upms.service.model.base.BaseUser;

import java.util.List;

/**
 * Generated by Jboot.
 */
@Table(tableName = "upms_user", primaryKey = "id")
public class User extends BaseUser<User> {

    public static final String CACHE_NAME = "upms_user";

}
