package net.ninemm.upms.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.upms.service.model.base.BaseUserGroupRel;

/**
 * Generated by Jboot.
 */
@Table(tableName = "upms_user_group_rel", primaryKey = "id")
public class UserGroupRel extends BaseUserGroupRel<UserGroupRel> {
	
}
