package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseAnswerValue;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_answer_value", primaryKey = "id")
public class AnswerValue extends BaseAnswerValue<AnswerValue> {
	
}
