package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseAnswer;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_answer", primaryKey = "id")
public class Answer extends BaseAnswer<Answer> {
	
}
