package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseAnswerSheet;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_answer_sheet", primaryKey = "id")
public class AnswerSheet extends BaseAnswerSheet<AnswerSheet> {
	
}
