package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseAnswerRestrict;

import java.io.Serializable;
import java.util.List;

/**
 * Generated by Jboot.
 * @author jy
 */
@Table(tableName = "survey_answer_restrict", primaryKey = "id")
public class AnswerRestrict extends BaseAnswerRestrict<AnswerRestrict>  {
    public static final String CACHE_NAME="survey_answer_restrict";

}
