package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseAttr;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_attr", primaryKey = "id")
public class Attr extends BaseAttr<Attr> {
    public static final String CACHE_NAME="survey_attr";
}
