package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseConsumer;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_consumer", primaryKey = "id")
public class Consumer extends BaseConsumer<Consumer> {
	
}
