package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseConsumerAttrCondition;

/**
 * Generated by Jboot.
 */
@Table(tableName = "consumer_attr_condition", primaryKey = "id")
public class ConsumerAttrCondition extends BaseConsumerAttrCondition<ConsumerAttrCondition> {
	
}
