package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseFrequencyCondition;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_frequency_condition", primaryKey = "id")
public class FrequencyCondition extends BaseFrequencyCondition<FrequencyCondition> {
	
}
