package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseProject;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_project", primaryKey = "id")
public class Project extends BaseProject<Project> {
	
}
