package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BasePublish;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_publish", primaryKey = "id")
public class Publish extends BasePublish<Publish> {
	
}
