package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseQuestionAttr;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_question_attr", primaryKey = "id")
public class QuestionAttr extends BaseQuestionAttr<QuestionAttr> {
	
}
