package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseQuestion;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_question", primaryKey = "id")
public class Question extends BaseQuestion<Question> {
	
}
