package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseSendRecord;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_send_record", primaryKey = "id")
public class SendRecord extends BaseSendRecord<SendRecord> {
	
}
