package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseShare;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_share", primaryKey = "id")
public class Share extends BaseShare<Share> {
	
}
