package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseStoreQuestion;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_store_question", primaryKey = "id")
public class StoreQuestion extends BaseStoreQuestion<StoreQuestion> {
	
}
