package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseSurvey;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey", primaryKey = "id")
public class Survey extends BaseSurvey<Survey> {
    public static final String CACHE_NAME="survey";
}
