package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseTag;

/**
 * Generated by Jboot.
 */
@Table(tableName = "tag", primaryKey = "id")
public class Tag extends BaseTag<Tag> {
	
}
