package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseTagMapping;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_tag_mapping", primaryKey = "id")
public class TagMapping extends BaseTagMapping<TagMapping> {
	
}
