package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseTags;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_tags", primaryKey = "id")
public class Tags extends BaseTags<Tags> {
    public static final String CACHE_NAME="survey_tags";
}
