package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseTaskAttachment;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_task_attachment", primaryKey = "id")
public class TaskAttachment extends BaseTaskAttachment<TaskAttachment> {
	
}
