package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseTask;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_task", primaryKey = "id")
public class Task extends BaseTask<Task> {
	public static final String CACHE_NAME = "survey_task";
}
