package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseTaskProcess;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_task_process", primaryKey = "id")
public class TaskProcess extends BaseTaskProcess<TaskProcess> {
	
}
