package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseTaskRel;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_task_rel", primaryKey = "id")
public class TaskRel extends BaseTaskRel<TaskRel> {
	
}
