package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseTemplateCategory;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_template_category", primaryKey = "id")
public class TemplateCategory extends BaseTemplateCategory<TemplateCategory> {
	
}
