package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseTemplate;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_template", primaryKey = "id")
public class Template extends BaseTemplate<Template> {
	
}
