package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseTimeCondition;

/**
 * Generated by Jboot.
 */
@Table(tableName = "survey_time_condition", primaryKey = "id")
public class TimeCondition extends BaseTimeCondition<TimeCondition> {
	
}
