package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseWxConfig;

/**
 * Generated by Jboot.
 */
@Table(tableName = "wx_config", primaryKey = "id")
public class WxConfig extends BaseWxConfig<WxConfig> {
	
}
