package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseWxPayOrder;

/**
 * Generated by Jboot.
 */
@Table(tableName = "wx_pay_order", primaryKey = "id")
public class WxPayOrder extends BaseWxPayOrder<WxPayOrder> {
	
}
