package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseWxRedpackConfig;

/**
 * Generated by Jboot.
 */
@Table(tableName = "wx_redpack_config", primaryKey = "id")
public class WxRedpackConfig extends BaseWxRedpackConfig<WxRedpackConfig> {
	
}
