package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseWxRedpackResult;

/**
 * Generated by Jboot.
 */
@Table(tableName = "wx_redpack_result", primaryKey = "id")
public class WxRedpackResult extends BaseWxRedpackResult<WxRedpackResult> {
	
}
