package net.ninemm.survey.service.model;

import io.jboot.db.annotation.Table;
import net.ninemm.survey.service.model.base.BaseWxUser;

/**
 * Generated by Jboot.
 */
@Table(tableName = "wx_user", primaryKey = "openid")
public class WxUser extends BaseWxUser<WxUser> {
	
}
