package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTagMapping<M extends BaseTagMapping<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setSurveyId(java.lang.String surveyId) {
		set("survey_id", surveyId);
	}
	
	public java.lang.String getSurveyId() {
		return getStr("survey_id");
	}

	public void setQuestionId(java.lang.String questionId) {
		set("question_id", questionId);
	}
	
	public java.lang.String getQuestionId() {
		return getStr("question_id");
	}

	public void setTagId(java.lang.String tagId) {
		set("tag_id", tagId);
	}
	
	public java.lang.String getTagId() {
		return getStr("tag_id");
	}

	public void setRowOptionId(java.lang.String rowOptionId) {
		set("row_option_id", rowOptionId);
	}
	
	public java.lang.String getRowOptionId() {
		return getStr("row_option_id");
	}

	public void setColOptionId(java.lang.String colOptionId) {
		set("col_option_id", colOptionId);
	}
	
	public java.lang.String getColOptionId() {
		return getStr("col_option_id");
	}

	public void setTagName(java.lang.String tagName) {
		set("tag_name", tagName);
	}
	
	public java.lang.String getTagName() {
		return getStr("tag_name");
	}

	public void setTagType(java.lang.String tagType) {
		set("tag_type", tagType);
	}
	
	public java.lang.String getTagType() {
		return getStr("tag_type");
	}

	public void setIsQuestionTag(java.lang.Integer isQuestionTag) {
		set("is_question_tag", isQuestionTag);
	}
	
	public java.lang.Integer getIsQuestionTag() {
		return getInt("is_question_tag");
	}

}
