package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxRedpackConfig<M extends BaseWxRedpackConfig<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setIsOpen(java.lang.Integer isOpen) {
		set("is_open", isOpen);
	}
	
	public java.lang.Integer getIsOpen() {
		return getInt("is_open");
	}

	public void setSurveyId(java.lang.String surveyId) {
		set("survey_id", surveyId);
	}
	
	public java.lang.String getSurveyId() {
		return getStr("survey_id");
	}

	public void setSendWay(java.lang.Integer sendWay) {
		set("send_way", sendWay);
	}
	
	public java.lang.Integer getSendWay() {
		return getInt("send_way");
	}

	public void setGetWay(java.lang.Integer getWay) {
		set("get_way", getWay);
	}
	
	public java.lang.Integer getGetWay() {
		return getInt("get_way");
	}

	public void setChanceValue(java.lang.Integer chanceValue) {
		set("chance_value", chanceValue);
	}
	
	public java.lang.Integer getChanceValue() {
		return getInt("chance_value");
	}

	public void setGetOnce(java.lang.Integer getOnce) {
		set("get_once", getOnce);
	}
	
	public java.lang.Integer getGetOnce() {
		return getInt("get_once");
	}

	public void setRedPackMoney(java.lang.Integer redPackMoney) {
		set("red_pack_money", redPackMoney);
	}
	
	public java.lang.Integer getRedPackMoney() {
		return getInt("red_pack_money");
	}

	public void setRedPackNum(java.lang.Integer redPackNum) {
		set("red_pack_num", redPackNum);
	}
	
	public java.lang.Integer getRedPackNum() {
		return getInt("red_pack_num");
	}

	public void setRedPackMin(java.lang.Integer redPackMin) {
		set("red_pack_min", redPackMin);
	}
	
	public java.lang.Integer getRedPackMin() {
		return getInt("red_pack_min");
	}

	public void setRedPackMax(java.lang.Integer redPackMax) {
		set("red_pack_max", redPackMax);
	}
	
	public java.lang.Integer getRedPackMax() {
		return getInt("red_pack_max");
	}

	public void setSendName(java.lang.String sendName) {
		set("send_name", sendName);
	}
	
	public java.lang.String getSendName() {
		return getStr("send_name");
	}

	public void setWishing(java.lang.String wishing) {
		set("wishing", wishing);
	}
	
	public java.lang.String getWishing() {
		return getStr("wishing");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setModifyUser(java.lang.String modifyUser) {
		set("modify_user", modifyUser);
	}
	
	public java.lang.String getModifyUser() {
		return getStr("modify_user");
	}

	public void setDeptId(java.lang.String deptId) {
		set("dept_id", deptId);
	}
	
	public java.lang.String getDeptId() {
		return getStr("dept_id");
	}

	public void setDataArea(java.lang.String dataArea) {
		set("data_area", dataArea);
	}
	
	public java.lang.String getDataArea() {
		return getStr("data_area");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
