package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCategory<M extends BaseCategory<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setCategoryName(java.lang.String categoryName) {
		set("category_name", categoryName);
	}
	
	public java.lang.String getCategoryName() {
		return getStr("category_name");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setCreaterId(java.lang.String createrId) {
		set("creater_id", createrId);
	}
	
	public java.lang.String getCreaterId() {
		return getStr("creater_id");
	}

	public void setCreaterName(java.lang.String createrName) {
		set("creater_name", createrName);
	}
	
	public java.lang.String getCreaterName() {
		return getStr("creater_name");
	}

	public void setDataArea(java.lang.String dataArea) {
		set("data_area", dataArea);
	}
	
	public java.lang.String getDataArea() {
		return getStr("data_area");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyUserId(java.lang.String modifyUserId) {
		set("modify_user_id", modifyUserId);
	}
	
	public java.lang.String getModifyUserId() {
		return getStr("modify_user_id");
	}

	public void setModifyUserName(java.lang.String modifyUserName) {
		set("modify_user_name", modifyUserName);
	}
	
	public java.lang.String getModifyUserName() {
		return getStr("modify_user_name");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
