package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAnswerValue<M extends BaseAnswerValue<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setSurveyId(java.lang.String surveyId) {
		set("survey_id", surveyId);
	}
	
	public java.lang.String getSurveyId() {
		return getStr("survey_id");
	}

	public void setAnswerSheetId(java.lang.String answerSheetId) {
		set("answer_sheet_id", answerSheetId);
	}
	
	public java.lang.String getAnswerSheetId() {
		return getStr("answer_sheet_id");
	}

	public void setQuestionId(java.lang.String questionId) {
		set("question_id", questionId);
	}
	
	public java.lang.String getQuestionId() {
		return getStr("question_id");
	}

	public void setOrderList(java.lang.Integer orderList) {
		set("order_list", orderList);
	}
	
	public java.lang.Integer getOrderList() {
		return getInt("order_list");
	}

	public void setScore(java.math.BigDecimal score) {
		set("score", score);
	}
	
	public java.math.BigDecimal getScore() {
		return get("score");
	}

	public void setRowOptionId(java.lang.String rowOptionId) {
		set("row_option_id", rowOptionId);
	}
	
	public java.lang.String getRowOptionId() {
		return getStr("row_option_id");
	}

	public void setRowOptionOrder(java.lang.Integer rowOptionOrder) {
		set("row_option_order", rowOptionOrder);
	}
	
	public java.lang.Integer getRowOptionOrder() {
		return getInt("row_option_order");
	}

	public void setColOptionId(java.lang.String colOptionId) {
		set("col_option_id", colOptionId);
	}
	
	public java.lang.String getColOptionId() {
		return getStr("col_option_id");
	}

	public void setColOptionOrder(java.lang.Integer colOptionOrder) {
		set("col_option_order", colOptionOrder);
	}
	
	public java.lang.Integer getColOptionOrder() {
		return getInt("col_option_order");
	}

	public void setListOptionId(java.lang.String listOptionId) {
		set("list_option_id", listOptionId);
	}
	
	public java.lang.String getListOptionId() {
		return getStr("list_option_id");
	}

	public void setOptionValue(java.lang.String optionValue) {
		set("option_value", optionValue);
	}
	
	public java.lang.String getOptionValue() {
		return getStr("option_value");
	}

	public void setIsCorrect(java.lang.Integer isCorrect) {
		set("is_correct", isCorrect);
	}
	
	public java.lang.Integer getIsCorrect() {
		return getInt("is_correct");
	}

}
