package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStyle<M extends BaseStyle<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setSurveyId(java.lang.String surveyId) {
		set("survey_id", surveyId);
	}
	
	public java.lang.String getSurveyId() {
		return getStr("survey_id");
	}

	public void setBackgroundImagePath(java.lang.String backgroundImagePath) {
		set("background_image_path", backgroundImagePath);
	}
	
	public java.lang.String getBackgroundImagePath() {
		return getStr("background_image_path");
	}

	public void setTextStyle(java.lang.String textStyle) {
		set("text_style", textStyle);
	}
	
	public java.lang.String getTextStyle() {
		return getStr("text_style");
	}

	public void setHeaderStyle(java.lang.String headerStyle) {
		set("header_style", headerStyle);
	}
	
	public java.lang.String getHeaderStyle() {
		return getStr("header_style");
	}

	public void setFooterStyle(java.lang.String footerStyle) {
		set("footer_style", footerStyle);
	}
	
	public java.lang.String getFooterStyle() {
		return getStr("footer_style");
	}

	public void setBackgroundColor(java.lang.String backgroundColor) {
		set("background_color", backgroundColor);
	}
	
	public java.lang.String getBackgroundColor() {
		return getStr("background_color");
	}

	public void setBackgroundColor1(java.lang.String backgroundColor1) {
		set("background_color1", backgroundColor1);
	}
	
	public java.lang.String getBackgroundColor1() {
		return getStr("background_color1");
	}

	public void setButtonColor(java.lang.String buttonColor) {
		set("button_color", buttonColor);
	}
	
	public java.lang.String getButtonColor() {
		return getStr("button_color");
	}

	public void setTitleStyle(java.lang.String titleStyle) {
		set("title_style", titleStyle);
	}
	
	public java.lang.String getTitleStyle() {
		return getStr("title_style");
	}

	public void setDescriptionStyle(java.lang.String descriptionStyle) {
		set("description_style", descriptionStyle);
	}
	
	public java.lang.String getDescriptionStyle() {
		return getStr("description_style");
	}

	public void setQuestionStyle(java.lang.String questionStyle) {
		set("question_style", questionStyle);
	}
	
	public java.lang.String getQuestionStyle() {
		return getStr("question_style");
	}

	public void setQuestionOptionStyle(java.lang.String questionOptionStyle) {
		set("question_option_style", questionOptionStyle);
	}
	
	public java.lang.String getQuestionOptionStyle() {
		return getStr("question_option_style");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setDeptId(java.lang.String deptId) {
		set("dept_id", deptId);
	}
	
	public java.lang.String getDeptId() {
		return getStr("dept_id");
	}

	public void setDataArea(java.lang.String dataArea) {
		set("data_area", dataArea);
	}
	
	public java.lang.String getDataArea() {
		return getStr("data_area");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
