package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSendRecord<M extends BaseSendRecord<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setSurveyId(java.lang.String surveyId) {
		set("survey_id", surveyId);
	}
	
	public java.lang.String getSurveyId() {
		return getStr("survey_id");
	}

	public void setSurveyPublishId(java.lang.String surveyPublishId) {
		set("survey_publish_id", surveyPublishId);
	}
	
	public java.lang.String getSurveyPublishId() {
		return getStr("survey_publish_id");
	}

	public void setShortLink(java.lang.String shortLink) {
		set("short_link", shortLink);
	}
	
	public java.lang.String getShortLink() {
		return getStr("short_link");
	}

	public void setOriginalLink(java.lang.String originalLink) {
		set("original_link", originalLink);
	}
	
	public java.lang.String getOriginalLink() {
		return getStr("original_link");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setIsSuccess(java.lang.Integer isSuccess) {
		set("is_success", isSuccess);
	}
	
	public java.lang.Integer getIsSuccess() {
		return getInt("is_success");
	}

	public void setSendTitle(java.lang.String sendTitle) {
		set("send_title", sendTitle);
	}
	
	public java.lang.String getSendTitle() {
		return getStr("send_title");
	}

	public void setSendAddress(java.lang.String sendAddress) {
		set("send_address", sendAddress);
	}
	
	public java.lang.String getSendAddress() {
		return getStr("send_address");
	}

	public void setIsAnswered(java.lang.Integer isAnswered) {
		set("is_answered", isAnswered);
	}
	
	public java.lang.Integer getIsAnswered() {
		return getInt("is_answered");
	}

	public void setAnsweredTime(java.util.Date answeredTime) {
		set("answered_time", answeredTime);
	}
	
	public java.util.Date getAnsweredTime() {
		return get("answered_time");
	}

	public void setConsumerId(java.lang.String consumerId) {
		set("consumer_id", consumerId);
	}
	
	public java.lang.String getConsumerId() {
		return getStr("consumer_id");
	}

	public void setConsumerName(java.lang.String consumerName) {
		set("consumer_name", consumerName);
	}
	
	public java.lang.String getConsumerName() {
		return getStr("consumer_name");
	}

	public void setConsumerSource(java.lang.Integer consumerSource) {
		set("consumer_source", consumerSource);
	}
	
	public java.lang.Integer getConsumerSource() {
		return getInt("consumer_source");
	}

	public void setSalesmanId(java.lang.String salesmanId) {
		set("salesman_id", salesmanId);
	}
	
	public java.lang.String getSalesmanId() {
		return getStr("salesman_id");
	}

	public void setSalesmanName(java.lang.String salesmanName) {
		set("salesman_name", salesmanName);
	}
	
	public java.lang.String getSalesmanName() {
		return getStr("salesman_name");
	}

	public void setResendNum(java.lang.Integer resendNum) {
		set("resend_num", resendNum);
	}
	
	public java.lang.Integer getResendNum() {
		return getInt("resend_num");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setDeptId(java.lang.String deptId) {
		set("dept_id", deptId);
	}
	
	public java.lang.String getDeptId() {
		return getStr("dept_id");
	}

	public void setDataArea(java.lang.String dataArea) {
		set("data_area", dataArea);
	}
	
	public java.lang.String getDataArea() {
		return getStr("data_area");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
