package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTemplate<M extends BaseTemplate<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setTemplateCategoryId(java.lang.String templateCategoryId) {
		set("template_category_id", templateCategoryId);
	}
	
	public java.lang.String getTemplateCategoryId() {
		return getStr("template_category_id");
	}

	public void setTemplateName(java.lang.String templateName) {
		set("template_name", templateName);
	}
	
	public java.lang.String getTemplateName() {
		return getStr("template_name");
	}

	public void setSurveyId(java.lang.String surveyId) {
		set("survey_id", surveyId);
	}
	
	public java.lang.String getSurveyId() {
		return getStr("survey_id");
	}

	public void setIsRandom(java.lang.Integer isRandom) {
		set("is_random", isRandom);
	}
	
	public java.lang.Integer getIsRandom() {
		return getInt("is_random");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setDeptId(java.lang.String deptId) {
		set("dept_id", deptId);
	}
	
	public java.lang.String getDeptId() {
		return getStr("dept_id");
	}

	public void setDataArea(java.lang.String dataArea) {
		set("data_area", dataArea);
	}
	
	public java.lang.String getDataArea() {
		return getStr("data_area");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
