package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTask<M extends BaseTask<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setProjectId(java.lang.String projectId) {
		set("project_id", projectId);
	}
	
	public java.lang.String getProjectId() {
		return getStr("project_id");
	}

	public void setTemplateCategoryId(java.lang.String templateCategoryId) {
		set("template_category_id", templateCategoryId);
	}
	
	public java.lang.String getTemplateCategoryId() {
		return getStr("template_category_id");
	}

	public void setTemplateId(java.lang.String templateId) {
		set("template_id", templateId);
	}
	
	public java.lang.String getTemplateId() {
		return getStr("template_id");
	}

	public void setPublisherId(java.lang.String publisherId) {
		set("publisher_id", publisherId);
	}
	
	public java.lang.String getPublisherId() {
		return getStr("publisher_id");
	}

	public void setPublisherName(java.lang.String publisherName) {
		set("publisher_name", publisherName);
	}
	
	public java.lang.String getPublisherName() {
		return getStr("publisher_name");
	}

	public void setStage(java.lang.Integer stage) {
		set("stage", stage);
	}
	
	public java.lang.Integer getStage() {
		return getInt("stage");
	}

	public void setDeptId(java.lang.String deptId) {
		set("dept_id", deptId);
	}
	
	public java.lang.String getDeptId() {
		return getStr("dept_id");
	}

	public void setDataArea(java.lang.String dataArea) {
		set("data_area", dataArea);
	}
	
	public java.lang.String getDataArea() {
		return getStr("data_area");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setEndDate(java.lang.String endDate) {
		set("end_date", endDate);
	}
	
	public java.lang.String getEndDate() {
		return getStr("end_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
