package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProject<M extends BaseProject<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setProjectName(java.lang.String projectName) {
		set("project_name", projectName);
	}
	
	public java.lang.String getProjectName() {
		return getStr("project_name");
	}

	public void setProjectCategory(java.lang.String projectCategory) {
		set("project_category", projectCategory);
	}
	
	public java.lang.String getProjectCategory() {
		return getStr("project_category");
	}
	
	public void setProjectCategoryName(java.lang.String projectCategoryName) {
		set("project_category_name", projectCategoryName);
	}
	
	public java.lang.String getProjectCategoryName() {
		return getStr("project_category_name");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setIsExtSurvey(java.lang.String isExtSurvey) {
		set("is_ext_survey", isExtSurvey);
	}
	
	public java.lang.String getIsExtSurvey() {
		return getStr("is_ext_survey");
	}

	public void setImportSurveyPos(java.lang.String importSurveyPos) {
		set("import_survey_pos", importSurveyPos);
	}
	
	public java.lang.String getImportSurveyPos() {
		return getStr("import_survey_pos");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setIsArchive(java.lang.String isArchive) {
		set("is_archive", isArchive);
	}
	
	public java.lang.String getIsArchive() {
		return getStr("is_archive");
	}

	public void setCreaterId(java.lang.String createrId) {
		set("creater_id", createrId);
	}
	
	public java.lang.String getCreaterId() {
		return getStr("creater_id");
	}

	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}
	
	public java.lang.String getRealname() {
		return getStr("realname");
	}

	public void setDeptId(java.lang.String deptId) {
		set("dept_id", deptId);
	}
	
	public java.lang.String getDeptId() {
		return getStr("dept_id");
	}

	public void setDataArea(java.lang.String dataArea) {
		set("data_area", dataArea);
	}
	
	public java.lang.String getDataArea() {
		return getStr("data_area");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
