package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTask<M extends BaseTask<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setProjectId(java.lang.String projectId) {
		set("project_id", projectId);
	}
	
	public java.lang.String getProjectId() {
		return getStr("project_id");
	}

	public void setTemplateCategoryId(java.lang.String templateCategoryId) {
		set("template_category_id", templateCategoryId);
	}
	
	public java.lang.String getTemplateCategoryId() {
		return getStr("template_category_id");
	}

	public void setViewerId(java.lang.String viewerId) {
		set("viewer_id", viewerId);
	}
	
	public java.lang.String getViewerId() {
		return getStr("viewer_id");
	}

	public void setViewerName(java.lang.String viewerName) {
		set("viewer_name", viewerName);
	}
	
	public java.lang.String getViewerName() {
		return getStr("viewer_name");
	}

	public void setTemplateId(java.lang.String templateId) {
		set("template_id", templateId);
	}
	
	public java.lang.String getTemplateId() {
		return getStr("template_id");
	}

	public void setPublisherId(java.lang.String publisherId) {
		set("publisher_id", publisherId);
	}
	
	public java.lang.String getPublisherId() {
		return getStr("publisher_id");
	}

	public void setPublisherName(java.lang.String publisherName) {
		set("publisher_name", publisherName);
	}
	
	public java.lang.String getPublisherName() {
		return getStr("publisher_name");
	}

	public void setAccepterId(java.lang.String accepterId) {
		set("accepter_id", accepterId);
	}
	
	public java.lang.String getAccepterId() {
		return getStr("accepter_id");
	}

	public void setAccepterName(java.lang.String accepterName) {
		set("accepter_name", accepterName);
	}
	
	public java.lang.String getAccepterName() {
		return getStr("accepter_name");
	}

	public void setAcceptTime(java.util.Date acceptTime) {
		set("accept_time", acceptTime);
	}
	
	public java.util.Date getAcceptTime() {
		return get("accept_time");
	}

	public void setReviewerId(java.lang.String reviewerId) {
		set("reviewer_id", reviewerId);
	}
	
	public java.lang.String getReviewerId() {
		return getStr("reviewer_id");
	}

	public void setReviewerName(java.lang.String reviewerName) {
		set("reviewer_name", reviewerName);
	}
	
	public java.lang.String getReviewerName() {
		return getStr("reviewer_name");
	}

	public void setDeptId(java.lang.String deptId) {
		set("dept_id", deptId);
	}
	
	public java.lang.String getDeptId() {
		return getStr("dept_id");
	}

	public void setDataArea(java.lang.String dataArea) {
		set("data_area", dataArea);
	}
	
	public java.lang.String getDataArea() {
		return getStr("data_area");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
