package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxConfig<M extends BaseWxConfig<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setIsOpen(java.lang.Integer isOpen) {
		set("is_open", isOpen);
	}
	
	public java.lang.Integer getIsOpen() {
		return getInt("is_open");
	}

	public void setCustomerName(java.lang.String customerName) {
		set("customer_name", customerName);
	}
	
	public java.lang.String getCustomerName() {
		return getStr("customer_name");
	}

	public void setDomain(java.lang.String domain) {
		set("domain", domain);
	}
	
	public java.lang.String getDomain() {
		return getStr("domain");
	}

	public void setAppid(java.lang.String appid) {
		set("appid", appid);
	}
	
	public java.lang.String getAppid() {
		return getStr("appid");
	}

	public void setAppsecret(java.lang.String appsecret) {
		set("appsecret", appsecret);
	}
	
	public java.lang.String getAppsecret() {
		return getStr("appsecret");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}
	
	public java.lang.String getToken() {
		return getStr("token");
	}

	public void setMessageencrypt(java.lang.Integer messageencrypt) {
		set("messageencrypt", messageencrypt);
	}
	
	public java.lang.Integer getMessageencrypt() {
		return getInt("messageencrypt");
	}

	public void setEncodingaeskey(java.lang.String encodingaeskey) {
		set("encodingaeskey", encodingaeskey);
	}
	
	public java.lang.String getEncodingaeskey() {
		return getStr("encodingaeskey");
	}

	public void setDeptId(java.lang.String deptId) {
		set("dept_id", deptId);
	}
	
	public java.lang.String getDeptId() {
		return getStr("dept_id");
	}

	public void setDataArea(java.lang.String dataArea) {
		set("data_area", dataArea);
	}
	
	public java.lang.String getDataArea() {
		return getStr("data_area");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
