package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAttr<M extends BaseAttr<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setSurveyId(java.lang.String surveyId) {
		set("survey_id", surveyId);
	}
	
	public java.lang.String getSurveyId() {
		return getStr("survey_id");
	}

	public void setIsShowTitle(java.lang.Integer isShowTitle) {
		set("is_show_title", isShowTitle);
	}
	
	public java.lang.Integer getIsShowTitle() {
		return getInt("is_show_title");
	}

	public void setIsShowAnswerSheetNum(java.lang.Integer isShowAnswerSheetNum) {
		set("is_show_answer_sheet_num", isShowAnswerSheetNum);
	}
	
	public java.lang.Integer getIsShowAnswerSheetNum() {
		return getInt("is_show_answer_sheet_num");
	}

	public void setIsShowPrePageBtn(java.lang.Integer isShowPrePageBtn) {
		set("is_show_pre_page_btn", isShowPrePageBtn);
	}
	
	public java.lang.Integer getIsShowPrePageBtn() {
		return getInt("is_show_pre_page_btn");
	}

	public void setIsShowQrcode(java.lang.Integer isShowQrcode) {
		set("is_show_qrcode", isShowQrcode);
	}
	
	public java.lang.Integer getIsShowQrcode() {
		return getInt("is_show_qrcode");
	}

	public void setIsShowProgressBar(java.lang.Integer isShowProgressBar) {
		set("is_show_progress_bar", isShowProgressBar);
	}
	
	public java.lang.Integer getIsShowProgressBar() {
		return getInt("is_show_progress_bar");
	}

	public void setPromptLang(java.lang.Integer promptLang) {
		set("prompt_lang", promptLang);
	}
	
	public java.lang.Integer getPromptLang() {
		return getInt("prompt_lang");
	}

	public void setSubmitBtnText(java.lang.String submitBtnText) {
		set("submit_btn_text", submitBtnText);
	}
	
	public java.lang.String getSubmitBtnText() {
		return getStr("submit_btn_text");
	}

	public void setPrePageBtnText(java.lang.String prePageBtnText) {
		set("pre_page_btn_text", prePageBtnText);
	}
	
	public java.lang.String getPrePageBtnText() {
		return getStr("pre_page_btn_text");
	}

	public void setNextPageBtnText(java.lang.String nextPageBtnText) {
		set("next_page_btn_text", nextPageBtnText);
	}
	
	public java.lang.String getNextPageBtnText() {
		return getStr("next_page_btn_text");
	}

	public void setIsSurveyTitleHtml(java.lang.Integer isSurveyTitleHtml) {
		set("is_survey_title_html", isSurveyTitleHtml);
	}
	
	public java.lang.Integer getIsSurveyTitleHtml() {
		return getInt("is_survey_title_html");
	}

	public void setIsSurveyDescHtml(java.lang.Integer isSurveyDescHtml) {
		set("is_survey_desc_html", isSurveyDescHtml);
	}
	
	public java.lang.Integer getIsSurveyDescHtml() {
		return getInt("is_survey_desc_html");
	}

	public void setObjectType(java.lang.String objectType) {
		set("object_type", objectType);
	}
	
	public java.lang.String getObjectType() {
		return getStr("object_type");
	}

}
