package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConsumerAttrCondition<M extends BaseConsumerAttrCondition<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setAnswerRestrictId(java.lang.String answerRestrictId) {
		set("answer_restrict_id", answerRestrictId);
	}
	
	public java.lang.String getAnswerRestrictId() {
		return getStr("answer_restrict_id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	public java.lang.String getValue() {
		return getStr("value");
	}

	public void setAnswerSheetNum(java.lang.Integer answerSheetNum) {
		set("answer_sheet_num", answerSheetNum);
	}
	
	public java.lang.Integer getAnswerSheetNum() {
		return getInt("answer_sheet_num");
	}

}
