package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAnswerSheet<M extends BaseAnswerSheet<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setSurveyId(java.lang.String surveyId) {
		set("survey_id", surveyId);
	}
	
	public java.lang.String getSurveyId() {
		return getStr("survey_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}
	
	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}
	
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public void setLat(java.math.BigDecimal lat) {
		set("lat", lat);
	}
	
	public java.math.BigDecimal getLat() {
		return get("lat");
	}

	public void setLon(java.math.BigDecimal lon) {
		set("lon", lon);
	}
	
	public java.math.BigDecimal getLon() {
		return get("lon");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}
	
	public java.lang.String getProvince() {
		return getStr("province");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

	public void setCountry(java.lang.String country) {
		set("country", country);
	}
	
	public java.lang.String getCountry() {
		return getStr("country");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("is_valid", isValid);
	}
	
	public java.lang.Integer getIsValid() {
		return getInt("is_valid");
	}

	public void setIsBreakPoint(java.lang.Integer isBreakPoint) {
		set("is_break_point", isBreakPoint);
	}
	
	public java.lang.Integer getIsBreakPoint() {
		return getInt("is_break_point");
	}

	public void setBrowserType(java.lang.String browserType) {
		set("browser_type", browserType);
	}
	
	public java.lang.String getBrowserType() {
		return getStr("browser_type");
	}

	public void setOsType(java.lang.String osType) {
		set("os_type", osType);
	}
	
	public java.lang.String getOsType() {
		return getStr("os_type");
	}

	public void setIsPreSubmit(java.lang.Integer isPreSubmit) {
		set("is_pre_submit", isPreSubmit);
	}
	
	public java.lang.Integer getIsPreSubmit() {
		return getInt("is_pre_submit");
	}

	public void setAnswerSheetFrom(java.lang.Integer answerSheetFrom) {
		set("answer_sheet_from", answerSheetFrom);
	}
	
	public java.lang.Integer getAnswerSheetFrom() {
		return getInt("answer_sheet_from");
	}

	public void setTotalScore(java.math.BigDecimal totalScore) {
		set("total_score", totalScore);
	}
	
	public java.math.BigDecimal getTotalScore() {
		return get("total_score");
	}

	public void setShorturl(java.lang.String shorturl) {
		set("shorturl", shorturl);
	}
	
	public java.lang.String getShorturl() {
		return getStr("shorturl");
	}

	public void setParams(java.lang.String params) {
		set("params", params);
	}
	
	public java.lang.String getParams() {
		return getStr("params");
	}

	public void setConsumerId(java.lang.String consumerId) {
		set("consumer_id", consumerId);
	}
	
	public java.lang.String getConsumerId() {
		return getStr("consumer_id");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
