package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAnswerRestrict<M extends BaseAnswerRestrict<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setSurveyId(java.lang.String surveyId) {
		set("survey_id", surveyId);
	}
	
	public java.lang.String getSurveyId() {
		return getStr("survey_id");
	}

	public void setIsBreakpoint(java.lang.Integer isBreakpoint) {
		set("is_breakpoint", isBreakpoint);
	}
	
	public java.lang.Integer getIsBreakpoint() {
		return getInt("is_breakpoint");
	}

	public void setIsPreView(java.lang.Integer isPreView) {
		set("is_pre_view", isPreView);
	}
	
	public java.lang.Integer getIsPreView() {
		return getInt("is_pre_view");
	}

	public void setIsFixStartTime(java.lang.Integer isFixStartTime) {
		set("is_fix_start_time", isFixStartTime);
	}
	
	public java.lang.Integer getIsFixStartTime() {
		return getInt("is_fix_start_time");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}
	
	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setIsFixEndTime(java.lang.Integer isFixEndTime) {
		set("is_fix_end_time", isFixEndTime);
	}
	
	public java.lang.Integer getIsFixEndTime() {
		return getInt("is_fix_end_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}
	
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setIsFixAnswerTime(java.lang.Integer isFixAnswerTime) {
		set("is_fix_answer_time", isFixAnswerTime);
	}
	
	public java.lang.Integer getIsFixAnswerTime() {
		return getInt("is_fix_answer_time");
	}

	public void setMaxAnswerTime(java.util.Date maxAnswerTime) {
		set("max_answer_time", maxAnswerTime);
	}
	
	public java.util.Date getMaxAnswerTime() {
		return get("max_answer_time");
	}

	public void setIsValidateCode(java.lang.Integer isValidateCode) {
		set("is_validate_code", isValidateCode);
	}
	
	public java.lang.Integer getIsValidateCode() {
		return getInt("is_validate_code");
	}

	public void setMaxAnswerSheetNum(java.lang.Integer maxAnswerSheetNum) {
		set("max_answer_sheet_num", maxAnswerSheetNum);
	}
	
	public java.lang.Integer getMaxAnswerSheetNum() {
		return getInt("max_answer_sheet_num");
	}

	public void setIsIpLimit(java.lang.Integer isIpLimit) {
		set("is_ip_limit", isIpLimit);
	}
	
	public java.lang.Integer getIsIpLimit() {
		return getInt("is_ip_limit");
	}

	public void setIsTermLimit(java.lang.Integer isTermLimit) {
		set("is_term_limit", isTermLimit);
	}
	
	public java.lang.Integer getIsTermLimit() {
		return getInt("is_term_limit");
	}

	public void setIsConsumerLimit(java.lang.Integer isConsumerLimit) {
		set("is_consumer_limit", isConsumerLimit);
	}
	
	public java.lang.Integer getIsConsumerLimit() {
		return getInt("is_consumer_limit");
	}

	public void setTerminalType(java.lang.Integer terminalType) {
		set("terminal_type", terminalType);
	}
	
	public java.lang.Integer getTerminalType() {
		return getInt("terminal_type");
	}

	public void setIsConsumerAttrLimit(java.lang.Integer isConsumerAttrLimit) {
		set("is_consumer_attr_limit", isConsumerAttrLimit);
	}
	
	public java.lang.Integer getIsConsumerAttrLimit() {
		return getInt("is_consumer_attr_limit");
	}

	public void setDeptId(java.lang.String deptId) {
		set("dept_id", deptId);
	}
	
	public java.lang.String getDeptId() {
		return getStr("dept_id");
	}

	public void setDataArea(java.lang.String dataArea) {
		set("data_area", dataArea);
	}
	
	public java.lang.String getDataArea() {
		return getStr("data_area");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
