package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxRedpackResult<M extends BaseWxRedpackResult<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setSurveyId(java.lang.String surveyId) {
		set("survey_id", surveyId);
	}
	
	public java.lang.String getSurveyId() {
		return getStr("survey_id");
	}

	public void setReturnCode(java.lang.String returnCode) {
		set("return_code", returnCode);
	}
	
	public java.lang.String getReturnCode() {
		return getStr("return_code");
	}

	public void setReturnMsg(java.lang.String returnMsg) {
		set("return_msg", returnMsg);
	}
	
	public java.lang.String getReturnMsg() {
		return getStr("return_msg");
	}

	public void setResultCode(java.lang.String resultCode) {
		set("result_code", resultCode);
	}
	
	public java.lang.String getResultCode() {
		return getStr("result_code");
	}

	public void setErrCode(java.lang.String errCode) {
		set("err_code", errCode);
	}
	
	public java.lang.String getErrCode() {
		return getStr("err_code");
	}

	public void setErrCodeDes(java.lang.String errCodeDes) {
		set("err_code_des", errCodeDes);
	}
	
	public java.lang.String getErrCodeDes() {
		return getStr("err_code_des");
	}

	public void setMchBillno(java.lang.String mchBillno) {
		set("mch_billno", mchBillno);
	}
	
	public java.lang.String getMchBillno() {
		return getStr("mch_billno");
	}

	public void setMchId(java.lang.String mchId) {
		set("mch_id", mchId);
	}
	
	public java.lang.String getMchId() {
		return getStr("mch_id");
	}

	public void setWxappid(java.lang.String wxappid) {
		set("wxappid", wxappid);
	}
	
	public java.lang.String getWxappid() {
		return getStr("wxappid");
	}

	public void setReOpenid(java.lang.String reOpenid) {
		set("re_openid", reOpenid);
	}
	
	public java.lang.String getReOpenid() {
		return getStr("re_openid");
	}

	public void setTotalAmount(java.lang.String totalAmount) {
		set("total_amount", totalAmount);
	}
	
	public java.lang.String getTotalAmount() {
		return getStr("total_amount");
	}

	public void setSendTime(java.util.Date sendTime) {
		set("send_time", sendTime);
	}
	
	public java.util.Date getSendTime() {
		return get("send_time");
	}

	public void setSendListId(java.lang.String sendListId) {
		set("send_list_id", sendListId);
	}
	
	public java.lang.String getSendListId() {
		return getStr("send_list_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setShortUrl(java.lang.String shortUrl) {
		set("short_url", shortUrl);
	}
	
	public java.lang.String getShortUrl() {
		return getStr("short_url");
	}

}
