package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfig<M extends BaseConfig<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setSurveyId(java.lang.String surveyId) {
		set("survey_id", surveyId);
	}
	
	public java.lang.String getSurveyId() {
		return getStr("survey_id");
	}

	public void setIsInformCreator(java.lang.Integer isInformCreator) {
		set("is_inform_creator", isInformCreator);
	}
	
	public java.lang.Integer getIsInformCreator() {
		return getInt("is_inform_creator");
	}

	public void setIsShowTestimonial(java.lang.Integer isShowTestimonial) {
		set("is_show_testimonial", isShowTestimonial);
	}
	
	public java.lang.Integer getIsShowTestimonial() {
		return getInt("is_show_testimonial");
	}

	public void setIsSendEmail(java.lang.Integer isSendEmail) {
		set("is_send_email", isSendEmail);
	}
	
	public java.lang.Integer getIsSendEmail() {
		return getInt("is_send_email");
	}

	public void setIsSendMessage(java.lang.Integer isSendMessage) {
		set("is_send_message", isSendMessage);
	}
	
	public java.lang.Integer getIsSendMessage() {
		return getInt("is_send_message");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setIsSetCustomUrl(java.lang.Integer isSetCustomUrl) {
		set("is_set_custom_url", isSetCustomUrl);
	}
	
	public java.lang.Integer getIsSetCustomUrl() {
		return getInt("is_set_custom_url");
	}

	public void setCustomUrl(java.lang.String customUrl) {
		set("custom_url", customUrl);
	}
	
	public java.lang.String getCustomUrl() {
		return getStr("custom_url");
	}

	public void setHasPassword(java.lang.Integer hasPassword) {
		set("has_password", hasPassword);
	}
	
	public java.lang.Integer getHasPassword() {
		return getInt("has_password");
	}

	public void setPasswordTips(java.lang.String passwordTips) {
		set("password_tips", passwordTips);
	}
	
	public java.lang.String getPasswordTips() {
		return getStr("password_tips");
	}

	public void setIsContentPublic(java.lang.Integer isContentPublic) {
		set("is_content_public", isContentPublic);
	}
	
	public java.lang.Integer getIsContentPublic() {
		return getInt("is_content_public");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

}
