package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTaskAttachment<M extends BaseTaskAttachment<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setTaskId(java.lang.String taskId) {
		set("task_id", taskId);
	}
	
	public java.lang.String getTaskId() {
		return getStr("task_id");
	}

	public void setAttachmentName(java.lang.String attachmentName) {
		set("attachment_name", attachmentName);
	}
	
	public java.lang.String getAttachmentName() {
		return getStr("attachment_name");
	}

	public void setAttachmentPath(java.lang.String attachmentPath) {
		set("attachment_path", attachmentPath);
	}
	
	public java.lang.String getAttachmentPath() {
		return getStr("attachment_path");
	}

	public void setDeptId(java.lang.String deptId) {
		set("dept_id", deptId);
	}
	
	public java.lang.String getDeptId() {
		return getStr("dept_id");
	}

	public void setDataArea(java.lang.String dataArea) {
		set("data_area", dataArea);
	}
	
	public java.lang.String getDataArea() {
		return getStr("data_area");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
