package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePublish<M extends BasePublish<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setSurveyId(java.lang.String surveyId) {
		set("survey_id", surveyId);
	}
	
	public java.lang.String getSurveyId() {
		return getStr("survey_id");
	}

	public void setShortLink(java.lang.String shortLink) {
		set("short_link", shortLink);
	}
	
	public java.lang.String getShortLink() {
		return getStr("short_link");
	}

	public void setOriginalLink(java.lang.String originalLink) {
		set("original_link", originalLink);
	}
	
	public java.lang.String getOriginalLink() {
		return getStr("original_link");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("is_valid", isValid);
	}
	
	public java.lang.Integer getIsValid() {
		return getInt("is_valid");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setDeptId(java.lang.String deptId) {
		set("dept_id", deptId);
	}
	
	public java.lang.String getDeptId() {
		return getStr("dept_id");
	}

	public void setDataArea(java.lang.String dataArea) {
		set("data_area", dataArea);
	}
	
	public java.lang.String getDataArea() {
		return getStr("data_area");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
