package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSurvey<M extends BaseSurvey<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setTitleRichText(java.lang.String titleRichText) {
		set("title_rich_text", titleRichText);
	}
	
	public java.lang.String getTitleRichText() {
		return getStr("title_rich_text");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}
	
	public java.lang.String getRealname() {
		return getStr("realname");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setDescriptionRichText(java.lang.String descriptionRichText) {
		set("description_rich_text", descriptionRichText);
	}
	
	public java.lang.String getDescriptionRichText() {
		return getStr("description_rich_text");
	}

	public void setCategoryId(java.lang.String categoryId) {
		set("category_id", categoryId);
	}
	
	public java.lang.String getCategoryId() {
		return getStr("category_id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setLogoPath(java.lang.String logoPath) {
		set("logo_path", logoPath);
	}
	
	public java.lang.String getLogoPath() {
		return getStr("logo_path");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setTotalQuestionNum(java.lang.Integer totalQuestionNum) {
		set("total_question_num", totalQuestionNum);
	}
	
	public java.lang.Integer getTotalQuestionNum() {
		return getInt("total_question_num");
	}

	public void setTotalAnswerSheetNum(java.lang.Integer totalAnswerSheetNum) {
		set("total_answer_sheet_num", totalAnswerSheetNum);
	}
	
	public java.lang.Integer getTotalAnswerSheetNum() {
		return getInt("total_answer_sheet_num");
	}

	public void setSingleShowType(java.lang.Integer singleShowType) {
		set("single_show_type", singleShowType);
	}
	
	public java.lang.Integer getSingleShowType() {
		return getInt("single_show_type");
	}

	public void setIsTag(java.lang.Integer isTag) {
		set("is_tag", isTag);
	}
	
	public java.lang.Integer getIsTag() {
		return getInt("is_tag");
	}

	public void setIsLock(java.lang.Integer isLock) {
		set("is_lock", isLock);
	}
	
	public java.lang.Integer getIsLock() {
		return getInt("is_lock");
	}

	public void setDeptId(java.lang.String deptId) {
		set("dept_id", deptId);
	}
	
	public java.lang.String getDeptId() {
		return getStr("dept_id");
	}

	public void setDataArea(java.lang.String dataArea) {
		set("data_area", dataArea);
	}
	
	public java.lang.String getDataArea() {
		return getStr("data_area");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
