package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAnswer<M extends BaseAnswer<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setSurveyId(java.lang.String surveyId) {
		set("survey_id", surveyId);
	}
	
	public java.lang.String getSurveyId() {
		return getStr("survey_id");
	}

	public void setAnswerSheetId(java.lang.String answerSheetId) {
		set("answer_sheet_id", answerSheetId);
	}
	
	public java.lang.String getAnswerSheetId() {
		return getStr("answer_sheet_id");
	}

	public void setQuestionId(java.lang.String questionId) {
		set("question_id", questionId);
	}
	
	public java.lang.String getQuestionId() {
		return getStr("question_id");
	}

	public void setCategory(java.lang.Integer category) {
		set("category", category);
	}
	
	public java.lang.Integer getCategory() {
		return getInt("category");
	}

	public void setSubCategory(java.lang.String subCategory) {
		set("sub_category", subCategory);
	}
	
	public java.lang.String getSubCategory() {
		return getStr("sub_category");
	}

	public void setScore(java.math.BigDecimal score) {
		set("score", score);
	}
	
	public java.math.BigDecimal getScore() {
		return get("score");
	}

}
