package net.ninemm.survey.service.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShare<M extends BaseShare<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setSurveyId(java.lang.String surveyId) {
		set("survey_id", surveyId);
	}
	
	public java.lang.String getSurveyId() {
		return getStr("survey_id");
	}

	public void setSurveyName(java.lang.String surveyName) {
		set("survey_name", surveyName);
	}
	
	public java.lang.String getSurveyName() {
		return getStr("survey_name");
	}

	public void setShareTouserId(java.lang.String shareTouserId) {
		set("share_touser_id", shareTouserId);
	}
	
	public java.lang.String getShareTouserId() {
		return getStr("share_touser_id");
	}

	public void setShareUserId(java.lang.String shareUserId) {
		set("share_user_id", shareUserId);
	}
	
	public java.lang.String getShareUserId() {
		return getStr("share_user_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setShareTime(java.util.Date shareTime) {
		set("share_time", shareTime);
	}
	
	public java.util.Date getShareTime() {
		return get("share_time");
	}

	public void setOperation(java.lang.Integer operation) {
		set("operation", operation);
	}
	
	public java.lang.Integer getOperation() {
		return getInt("operation");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public void setDeptId(java.lang.String deptId) {
		set("dept_id", deptId);
	}
	
	public java.lang.String getDeptId() {
		return getStr("dept_id");
	}

	public void setDataArea(java.lang.String dataArea) {
		set("data_area", dataArea);
	}
	
	public java.lang.String getDataArea() {
		return getStr("data_area");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}
	
	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
